# Pandas.factorize()
  - factorize(values, sort=False, na_sentinel=- 1, size_hint=None)
  - Encode the object as an enumerated type or categorical variable.
     - This method is useful for obtaining a numeric representation of an array 
       - when all that matters is identifying distinct values.  
  - Parameters:
     - values : 1D sequence.
     - sort : [bool, Default is False] Sort uniques and shuffle labels.
     - na_sentinel : [ int, default -1] Missing Values to mark ‘not found’.
     - Return: Numeric representation of array
   - https://www.geeksforgeeks.org/python-pandas-factorize/
   - https://pandas.pydata.org/docs/reference/api/pandas.factorize.html 


In [8]:

# importing libraries
import numpy as np
import pandas as pd
from pandas.api.types import CategoricalDtype


In [5]:
l_inp = ['b', 'd', 'd', 'c', 'a', 'c', 'a', 'b']
list(set((k,l_inp.count(k)) for k in l_inp))



[('d', 2), ('a', 2), ('b', 2), ('c', 2)]

In [9]:

"""
b: 0; d: 1; c: 2;  a:4
"""bels, uniques = pd.factorize(l_inp)
print("Numeric Representation : \n", labels)
print("Unique Values : \n", uniques)

Numeric Representation : 
 [0 1 1 2 3 2 3 0]
Unique Values : 
 ['b' 'd' 'c' 'a']


In [10]:
# sorting the numerics
label1, unique1 = pd.factorize(['b', 'd', 'd', 'c', 'a', 'c', 'a', 'b'], 
                                                           sort = True)
  
print("\n\nNumeric Representation : \n", label1)
print("Unique Values : \n", unique1)



Numeric Representation : 
 [1 3 3 2 0 2 0 1]
Unique Values : 
 ['a' 'b' 'c' 'd']


In [11]:
# Missing values indicated
label2, unique2 = pd.factorize(['b', None, 'd', 'c', None, 'a', ], 
                                              na_sentinel = -101)
  
print("\n\nNumeric Representation : \n", label2)
print("Unique Values : \n", unique2)



Numeric Representation : 
 [   0 -101    1    2 -101    3]
Unique Values : 
 ['b' 'd' 'c' 'a']


In [12]:

# When factorizing pandas object; unique will differ 
a = pd.Categorical(['a', 'a', 'c'], categories =['a', 'b', 'c'])  # ????
  
label3, unique3 = pd.factorize(a)
  
print("\n\nNumeric Representation : \n", label3)
print("Unique Values : \n", unique3)



Numeric Representation : 
 [0 0 1]
Unique Values : 
 ['a', 'c']
Categories (3, object): ['a', 'b', 'c']
