___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# LDA_summary_topic_model
   - Latent Dirichlet Allocation

In [3]:
import pandas as pd
import numpy as np
import pprint
from pprint import pprint
from sklearn.model_selection import RandomizedSearchCV
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
import random

## Data

We will be using Cluster_Summaries_0627.xlsx

In [4]:
path = 'C:\\users\\iny2819\\kroger\\Data\\'
sumy = pd.read_excel( path + 'Cluster_Summaries_0627.xlsx',sheet_name = 'Cluster_Summaries_0627')

In [24]:
sumy.shape

(8880, 9)

In [25]:
sumy.head()

ClusterLabel                                       Cluster Name  \
0             0  KITCHEN/DINING,HOME OFFICE,UPHOLSTERED GROUPS/...   
1             1  ART & CRAFT SUPPLIES,WALL ART,PLANT STANDS & A...   
2             2  KITCHEN/DINING,ACCENT FURNITURE,PLANT STANDS &...   
3             3  OSU COLLEGIATE,UO COLLEGIATE,BOISE STATE UNIVE...   
4             4  FASHION SOCKS,NCAA OTHER,NFL (NON SEAHAWKS),HO...   

   Cluster Size  ITM_ID  PMY_DPT_DSC  REC_DPT_DSC  DPT_DSC  COM_DSC  \
0          2299    2299            1            1        8       12   
1          1471    1471            1            1        7       10   
2          1413    1413            1            1       10       14   
3          1063    1063            1            1       12       25   
4          1027    1027            1            1       13       41   

   SUBCOM_DSC  
0          20  
1          11  
2          22  
3          39  
4          86

Notice how we don't have the topic of the articles! Let's use LDA to attempt to figure out clusters of the articles.

In [ ]:
# Define Search Param
search_params = {'n_components': [7, 10, 15, 20, 25, 30], 'learning_decay': [.5, .7, .9]}

# Init the Model
lda = LatentDirichletAllocation()

# Init Grid Search Class
#model = GridSearchCV(lda, param_grid=search_params)
model = RandomizedSearchCV(lda, param_distributions=search_params)
# Do the Grid Search
model.fit(dtm)

## Preprocessing

**`max_df`**` : float in range [0.0, 1.0] or int, default=1.0`<br>
When building the vocabulary ignore terms that have a document frequency strictly higher than the given threshold (corpus-specific stop words). If float, the parameter represents a proportion of documents, integer absolute counts. This parameter is ignored if vocabulary is not None.

**`min_df`**` : float in range [0.0, 1.0] or int, default=1`<br>
When building the vocabulary ignore terms that have a document frequency strictly lower than the given threshold. This value is also called cut-off in the literature. If float, the parameter represents a proportion of documents, integer absolute counts. This parameter is ignored if vocabulary is not None.

In [5]:
cv = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')

In [6]:
dtm = cv.fit_transform(sumy['Cluster Name'])

In [7]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

## LDA

In [7]:
# Define Search Param
search_params = {'n_components': [7, 10, 15, 20, 25, 30], 'learning_decay': [.5, .7, .9]}

# Init the Model
lda = LatentDirichletAllocation()

# Init Grid Search Class
#model = GridSearchCV(lda, param_grid=search_params)
model = RandomizedSearchCV(lda, param_distributions=search_params)
# Do the Grid Search
model.fit(dtm)

RandomizedSearchCV(estimator=LatentDirichletAllocation(),
                   param_distributions={'learning_decay': [0.5, 0.7, 0.9],
                                        'n_components': [7, 10, 15, 20, 25,
                                                         30]})

In [8]:
 print ('Best parameters: %s' % model.best_params_)

Best parameters: {'n_components': 25, 'learning_decay': 0.5}


In [9]:
# Log Likelihood Score
print("Best Log Likelihood Score: ", model.best_score_)

Best Log Likelihood Score:  -58641.86360795966


In [10]:
# Perplexity
best_lda_model = model.best_estimator_
print("Model Perplexity: ", best_lda_model.perplexity(dtm))

Model Perplexity:  132.4199530707927


In [28]:
LDA = LatentDirichletAllocation(n_components=10,random_state=42)

In [29]:
# This can take awhile, we're dealing with a large amount of documents!
LDA.fit(dtm)

LatentDirichletAllocation(random_state=42)

## Showing Stored Words

In [41]:
len(cv.get_feature_names_out())

755

In [42]:
import random

In [43]:
for i in range(10):
    random_word_id = random.randint(0,54776)
    print(cv.get_feature_names()[random_word_id])

cred
fairly
occupational
temer
tamil
closest
condone
breathes
tendrils
pivot


In [44]:
for i in range(10):
    random_word_id = random.randint(0,54776)
    print(cv.get_feature_names()[random_word_id])

foremothers
mocoa
ellroy
liron
ally
discouraged
utterance
provo
videgaray
archivist


### Showing Top Words Per Topic

In [31]:
len(LDA.components_)

10

In [47]:
LDA.components_

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [32]:
len(LDA.components_[0])

755

In [33]:
single_topic = LDA.components_[0]

In [35]:
# Returns the indices that would sort this array.
single_topic.argsort()

array([492, 364, 216, 616, 716, 246, 723, 402, 291, 523,  80, 697, 540,
       370,  10, 289, 171, 611, 459, 682, 218, 159, 621, 647, 180, 334,
       449, 207, 481, 752, 704, 681, 423, 646, 156, 626, 214, 457, 690,
       230, 299,  40, 374, 726,  17, 460, 257, 285,  44, 128, 596, 322,
       106, 471, 413, 609, 444, 500, 607, 631, 292, 499, 397, 255, 318,
       593, 112, 341, 452, 215, 143, 321, 433,  21,  20, 183, 437, 396,
       511, 539, 532, 209, 692, 194, 625, 166, 733, 395, 483, 354, 651,
       548, 506, 310, 239, 203, 708, 617,   8, 620, 175, 504, 719, 592,
       622, 597, 537, 678, 664, 479, 510, 324, 237, 327, 573, 728, 196,
       602,  48, 201, 217, 229, 643, 189, 705, 131, 658, 233,  27, 507,
       205, 661, 464,  56, 623, 653, 142, 347, 732, 221, 720, 731, 603,
       280,  28, 534, 525, 687, 182,  98, 346,  68, 715, 272, 309, 296,
       568,  95, 116, 302, 496, 744,  93, 478, 304, 703, 387, 753, 372,
       177, 589, 357, 721, 689, 118, 406, 410, 178, 165, 528, 26

In [36]:
# Word least representative of this topic
single_topic[492]

0.10000000009316022

In [52]:
# Word most representative of this topic
single_topic[42993]

6247.245510521082

In [37]:
# Top 10 words for this topic:
single_topic.argsort()[-10:]

array([191, 642, 583, 743, 392, 405, 355, 610, 362, 675], dtype=int64)

In [38]:
top_word_indices = single_topic.argsort()[-10:]

In [42]:
for index in top_word_indices:
    print(cv.get_feature_names_out()[index])

dresses
tanks
sleep
wovens
ls
mens
jr
ss
knit
tops


These look like business articles perhaps... Let's confirm by using .transform() on our vectorized articles to attach a label number. But first, let's view all the 10 topics found.

In [40]:
for index,topic in enumerate(LDA.components_):
    print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
    print([cv.get_feature_names_out()[i] for i in topic.argsort()[-15:]])
    print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['label', 'ym', 'shells', 'fleece', 'sweaters', 'dresses', 'tanks', 'sleep', 'wovens', 'ls', 'mens', 'jr', 'ss', 'knit', 'tops']


THE TOP 15 WORDS FOR TOPIC #1
['models', 'preschool', 'summer', 'games', 'dolls', 'figures', 'action', 'diy', 'fisher', 'price', 'electrical', 'collegiate', 'creative', 'play', 'toys']


THE TOP 15 WORDS FOR TOPIC #2
['casuals', 'athletic', 'ladies', 'linens', 'accessories', 'table', 'pillows', 'trim', 'decorative', 'accents', 'novelty', 'tree', 'seasonal', 'skechers', 'decor']


THE TOP 15 WORDS FOR TOPIC #3
['use', 'general', 'fasteners', 'special', 'seasonal', 'sports', 'events', 'openstock', 'accessories', 'misc', 'hand', 'power', 'gadgets', 'basic', 'tools']


THE TOP 15 WORDS FOR TOPIC #4
['bath', 'restricted', 'age', 'heavy', 'dvds', 'outerwear', 'weight', 'sbt', 'souvenirs', 'accent', 'stands', 'plant', 'accessories', 'area', 'rugs']


THE TOP 15 WORDS FOR TOPIC #5
['upholstered', 'jar', 'candles', 'bedroom', 'office', 

### Attaching Discovered Topic Labels to Original Articles

In [57]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [43]:
dtm.shape

(8880, 755)

In [59]:
len(npr)

11992

In [44]:
topic_results = LDA.transform(dtm)

In [45]:
topic_results.shape

(8880, 10)

In [46]:
topic_results[0]

array([0.01      , 0.01      , 0.01      , 0.01      , 0.01000086,
       0.90999847, 0.01000024, 0.01000043, 0.01      , 0.01      ])

In [47]:
topic_results[0].round(2)

array([0.01, 0.01, 0.01, 0.01, 0.01, 0.91, 0.01, 0.01, 0.01, 0.01])

In [48]:
topic_results[0].argmax()

5

This means that our model thinks that the first article belongs to topic #1.

### Combining with Original Data

In [50]:
sumy.head()

ClusterLabel                                       Cluster Name  \
0             0  KITCHEN/DINING,HOME OFFICE,UPHOLSTERED GROUPS/...   
1             1  ART & CRAFT SUPPLIES,WALL ART,PLANT STANDS & A...   
2             2  KITCHEN/DINING,ACCENT FURNITURE,PLANT STANDS &...   
3             3  OSU COLLEGIATE,UO COLLEGIATE,BOISE STATE UNIVE...   
4             4  FASHION SOCKS,NCAA OTHER,NFL (NON SEAHAWKS),HO...   

   Cluster Size  ITM_ID  PMY_DPT_DSC  REC_DPT_DSC  DPT_DSC  COM_DSC  \
0          2299    2299            1            1        8       12   
1          1471    1471            1            1        7       10   
2          1413    1413            1            1       10       14   
3          1063    1063            1            1       12       25   
4          1027    1027            1            1       13       41   

   SUBCOM_DSC  
0          20  
1          11  
2          22  
3          39  
4          86

In [51]:
topic_results.argmax(axis=1)

array([5, 4, 5, ..., 5, 3, 8], dtype=int64)

In [54]:
sumy['Topic'] = topic_results.argmax(axis=1)

In [55]:
sumy.head(10)

ClusterLabel                                       Cluster Name  \
0             0  KITCHEN/DINING,HOME OFFICE,UPHOLSTERED GROUPS/...   
1             1  ART & CRAFT SUPPLIES,WALL ART,PLANT STANDS & A...   
2             2  KITCHEN/DINING,ACCENT FURNITURE,PLANT STANDS &...   
3             3  OSU COLLEGIATE,UO COLLEGIATE,BOISE STATE UNIVE...   
4             4  FASHION SOCKS,NCAA OTHER,NFL (NON SEAHAWKS),HO...   
5             5  ASSORTED GARDEN,PATIO ACCESSORIES,SMALL ACCESS...   
6             6  GARDEN HARDSCAPES,WALL ART,CREATIVE PLAY TOYS,...   
7             7  JAR CANDLES,WARMERS/WAX MELTS/FLAMELESS,ESSENT...   
8             8  TAPE & MAILING PRODUCTS,TAPE,PLUMBING REPAIR,A...   
9             9  UPHOLSTERED GROUPS/RECLINERS,ACCENT FURNITURE,...   

   Cluster Size  ITM_ID  PMY_DPT_DSC  REC_DPT_DSC  DPT_DSC  COM_DSC  \
0          2299    2299            1            1        8       12   
1          1471    1471            1            1        7       10   
2          1413    1413            1            1       10       14   
3          1063    1063            1            1       12       25   
4          1027    1027            1            1       13       41   
5           980     980            1            1       11       28   
6           953     953            1            1        4        4   
7           945     945            1            1       12       23   
8           944     944            1            1       13       46   
9           820     820            1            1        5        6   

   SUBCOM_DSC  Topic  
0          20      5  
1          11      4  
2          22      5  
3          39      1  
4          86      8  
5          37      5  
6           4      1  
7          34      1  
8          61      2  
9          10      5

In [56]:
sumy.to_csv(path + 'Cluster_Summaries_063023.csv',  index=None)

## Great work!